apiVersion: v1
kind: Service
metadata:
  name: {{ include "cert-manager-istio-csr.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "cert-manager-istio-csr.name" . }}
    {{- include "cert-manager-istio-csr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.server.serving.port }}
{{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
      protocol: TCP
      name: web
  selector:
    app: {{ include "cert-manager-istio-csr.name" . }}
