replicaCount: 2

service:
  port: 443
  type: NodePort
  nodePort: 30443

app:
  logFormat: json
  logLevel: 5

  certmanager:
    namespace: istio-system
    # WARNING: do not enable this option in production, or environments with
    # any non-trivial number of workloads for an extended period of time. Doing
    # so will balloon the resource consumption of both ETCD and the API server,
    # leading to errors and slow down. This option is intended for debugging
    # purposes only, for limited periods of time.
    preserveCertificateRequests: true
    additionalAnnotations:
    - name: custom.cert-manager.io/policy-name
      value: istio-csr
    - name: custom.cert-manager.io/second-annotation
      value: some-value
    issuer:
      # Explicitly blanked out to test "pure" runtime configuration
      group: ""
      kind: ""
      name: ""

  tls:
    trustDomain: foo.bar
    istiodCertificateEnable: "dynamic"
    certificateDuration: 20s
    certificateDNSNames:
    # Name used by the e2e client
    - istio-csr.cert-manager.svc
    # Name used within the demo cluster
    - cert-manager-istio-csr.cert-manager.svc

  server:
    maxCertificateDuration: 5m
    serving:
      address: 0.0.0.0
      port: 6443

resources: {}
